const path = require("path");
const root = __dirname;
module.exports = {
  apps: [
    {
      name: "playwright-display",
      cwd: root,
      script: path.join(root, "scripts/xvfb-start.sh"),
      interpreter: "none",
      autorestart: true,
      restart_delay: 2000,
    },
    {
      name: "playwright-selkies",
      cwd: root,
      script: path.join(root, "scripts/selkies-start.sh"),
      interpreter: "/bin/bash",
      autorestart: true,
      min_uptime: "5s",
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: "playwright-browser",
      cwd: root,
      script: path.join(root, "scripts/browser-gui.sh"),
      interpreter: "none",
      autorestart: true,
      restart_delay: 3000,
    },
    {
      name: "playwright-role-ui",
      cwd: root,
      script: path.join(root, "scripts/role-ui-start.sh"),
      interpreter: "/bin/bash",
      autorestart: true,
      min_uptime: "5s",
      max_restarts: 20,
      restart_delay: 1000,
    },
    {
      name: "playwright-dashboard",
      cwd: root,
      script: path.join(root, "scripts/dashboard-start.sh"),
      interpreter: "/bin/bash",
      autorestart: true,
      min_uptime: "5s",
      max_restarts: 20,
      restart_delay: 1000,
    },
    {
      name: "playwright-cdpa-worker",
      cwd: root,
      script: path.join(root, "scripts/cdpa-worker-start.sh"),
      interpreter: "/bin/bash",
      autorestart: true,
      min_uptime: "5s",
      max_restarts: 20,
      restart_delay: 1000,
    },
  ],
};
